name: Build Resume

on:
  push:
    paths:
      - 'cv.md'
      - '.github/workflows/build-cv.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pandoc + PDF support
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Create output directory
        run: mkdir -p dist

      - name: Generate DOCX (with Word style)
        run: |
          pandoc cv.md -o dist/cv.docx \
            --reference-doc=templates/style.docx

      - name: Copy styles to dist
        run: cp styles/cv.css dist/

      - name: Generate HTML 
        run: |
          pandoc cv.md -o dist/cv.html \
            --standalone \
            --css=cv.css

      - name: Install wkhtmltopdf
        run: sudo apt-get install -y wkhtmltopdf


      - name: Generate PDF from styled HTML
        run: |
          HTML_FILE="$(pwd)/dist/cv.html"
          HTML_URI="file://$HTML_FILE"
      
          # Debug actual file content (use local path)
          cat "$HTML_FILE"
      
          # Then use wkhtmltopdf with file:// URI
          wkhtmltopdf --enable-local-file-access "$HTML_URI" dist/cv.pdf

      - name: Upload resume artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resume-files
          path: dist/

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./dist
      
