name: Build Resume

on:
  push:
    paths:
      - 'cv.md'
      - '.github/workflows/build-cv.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Install Pandoc
      #   run: sudo apt-get update && sudo apt-get install -y pandoc

      - name: Install Pandoc + PDF support
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex

      - name: Create output directory
        run: mkdir -p dist

      - name: Generate DOCX (with Word style)
        run: |
          pandoc cv.md -o dist/cv.docx \
            --reference-doc=templates/style.docx

      # - name: Generate DOCX (with Word style)
      #   run: |
      #     pandoc cv.md -o dist/cv.docx --lua-filter=templates/fix-bullets.lua --reference-doc=templates/style.docx

      - name: Generate HTML (with CSS)
        run: |
          pandoc cv.md -o dist/cv.html \
            --standalone \
            --css=styles/cv.css \
            --metadata title="Mark Mitchell – Resume"

      # - name: Generate PDF (fallback)
      #   run: pandoc cv.md -o dist/cv.pdf

      # - name: Generate PDF from DOCX
      #   run: pandoc dist/cv.docx -o dist/cv2.pdf

      # - name: Install LibreOffice
      #   run: sudo apt-get install -y libreoffice
      
      # - name: Convert DOCX to PDF
      #   run: libreoffice --headless --convert-to pdf dist/cv.docx --outdir dist/

      - name: Install wkhtmltopdf
        run: sudo apt-get install -y wkhtmltopdf

      - name: Generate PDF from styled HTML
        run: wkhtmltopdf dist/cv.html dist/cv.pdf
    

      - name: Upload resume artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resume-files
          path: dist/

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./dist
