# .github/workflows/build-cv.yml
name: Build CV

on:
  push:
    paths:
      - 'cv.md'
      - '.github/workflows/build-cv.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Pandoc
        run: sudo apt-get install pandoc texlive-xetex -y

      - name: Create output directory
        run: mkdir -p dist    

      - name: Generate HTML
        run: pandoc cv.md -o dist/cv.html

      - name: Generate PDF
        run: pandoc cv.md -o dist/cv.pdf

      - name: Generate DOCX
        run: pandoc cv.md -o dist/cv.docx

      - name: Upload CV files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resume-files
          path: dist/

          #- name: Upload to GitHub Pages
          #uses: peaceiris/actions-gh-pages@v3
          #with:
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          #publish_dir: ./dist
